export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: 'Electronics' | 'Groceries' | 'Fashion' | 'Home Goods';
  rating: number;
  reviews: number;
  brand: string;
  inStock: boolean;
};

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Wireless Noise-Cancelling Headphones',
    description: 'Immerse yourself in music with these high-fidelity wireless headphones. Featuring active noise cancellation and a 30-hour battery life.',
    price: 249.99,
    image: 'https://picsum.photos/600/600?random=1',
    category: 'Electronics',
    rating: 5,
    reviews: 125,
    brand: 'SoundWave',
    inStock: true,
  },
  {
    id: 'prod_002',
    name: 'Organic Avocadoes (4-pack)',
    description: 'Fresh, creamy, and organically grown. Perfect for toast, salads, or guacamole.',
    price: 5.99,
    image: 'https://picsum.photos/600/600?random=2',
    category: 'Groceries',
    rating: 4,
    reviews: 88,
    brand: 'MyMart Fresh',
    inStock: true,
  },
  {
    id: 'prod_003',
    name: 'Classic Cotton T-Shirt',
    description: 'A wardrobe staple. Made from 100% premium, soft-touch cotton for ultimate comfort.',
    price: 29.99,
    image: 'https://picsum.photos/600/600?random=3',
    category: 'Fashion',
    rating: 5,
    reviews: 210,
    brand: 'Urban Threads',
    inStock: true,
  },
  {
    id: 'prod_004',
    name: 'Smart LED Desk Lamp',
    description: 'Adjustable brightness and color temperature to suit your mood. Control via app or voice assistant.',
    price: 45.50,
    image: 'https://picsum.photos/600/600?random=4',
    category: 'Home Goods',
    rating: 4,
    reviews: 67,
    brand: 'CozyHome',
    inStock: false,
  },
  {
    id: 'prod_005',
    name: '4K Ultra HD Smart TV',
    description: 'Experience breathtaking clarity and vibrant colors. Stream your favorite shows from all major platforms.',
    price: 499.99,
    image: 'https://picsum.photos/600/600?random=5',
    category: 'Electronics',
    rating: 5,
    reviews: 302,
    brand: 'Visionary',
    inStock: true,
  },
  {
    id: 'prod_006',
    name: 'Artisanal Sourdough Bread',
    description: 'Handcrafted with a traditional starter. A crispy crust and a soft, airy interior.',
    price: 7.49,
    image: 'https://picsum.photos/600/600?random=6',
    category: 'Groceries',
    rating: 5,
    reviews: 150,
    brand: 'The Bakehouse',
    inStock: true,
  },
  {
    id: 'prod_007',
    name: 'Leather Messenger Bag',
    description: 'Stylish and durable, this genuine leather bag is perfect for work or travel. Fits a 15-inch laptop.',
    price: 120.00,
    image: 'https://picsum.photos/600/600?random=7',
    category: 'Fashion',
    rating: 4,
    reviews: 55,
    brand: 'Nomad Gear',
    inStock: true,
  },
  {
    id: 'prod_008',
    name: 'Plush Velvet Throw Pillow',
    description: 'Add a touch of elegance to your living space with this luxuriously soft velvet pillow.',
    price: 35.00,
    image: 'https://picsum.photos/600/600?random=8',
    category: 'Home Goods',
    rating: 5,
    reviews: 42,
    brand: 'CozyHome',
    inStock: true,
  },
  {
    id: 'prod_009',
    name: 'Portable Bluetooth Speaker',
    description: 'Take your music anywhere. This speaker is waterproof, dustproof, and has a 12-hour playtime.',
    price: 79.99,
    image: 'https://picsum.photos/600/600?random=9',
    category: 'Electronics',
    rating: 4,
    reviews: 98,
    brand: 'SoundWave',
    inStock: true,
  },
  {
    id: 'prod_010',
    name: 'Gourmet Coffee Beans',
    description: 'A rich and aromatic medium roast blend, ethically sourced from single-origin farms.',
    price: 18.99,
    image: 'https://picsum.photos/600/600?random=10',
    category: 'Groceries',
    rating: 5,
    reviews: 189,
    brand: 'The Daily Grind',
    inStock: true,
  },
  {
    id: 'prod_011',
    name: 'Performance Running Shoes',
    description: 'Lightweight and responsive, engineered for speed and comfort on your daily runs.',
    price: 130.00,
    image: 'https://picsum.photos/600/600?random=11',
    category: 'Fashion',
    rating: 5,
    reviews: 164,
    brand: 'Apex Runners',
    inStock: true,
  },
  {
    id: 'prod_012',
    name: 'Scented Soy Wax Candle',
    description: 'Create a relaxing ambiance with this lavender and chamomile scented candle. 50-hour burn time.',
    price: 24.99,
    image: 'https://picsum.photos/600/600?random=12',
    category: 'Home Goods',
    rating: 4,
    reviews: 73,
    brand: 'CozyHome',
    inStock: false,
  },
];

export const categories = [...new Set(products.map((p) => p.category))];
export const brands = [...new Set(products.map((p) => p.brand))];
